blueprint:
  name: Proteção de Tensão Tomada (Fail-Safe v4)
  description: Proteção contra subtensão e sobretensão com lógica defensiva.
  domain: automation

  input:
    plug:
      name: Tomada
      selector:
        entity:
          domain: switch

    voltage_sensor:
      name: Sensor de Tensão
      selector:
        entity:
          domain: sensor

    surge_counter:
      name: Contador de Surtos
      selector:
        entity:
          domain: counter

    notify_device:
      name: Dispositivo para notificação
      selector:
        device:
          integration: mobile_app

    cut_below:
      name: Limite inferior de corte (V)
      default: 115
      selector:
        number:
          min: 80
          max: 200
          unit_of_measurement: V

    cut_above:
      name: Limite superior de corte (V)
      default: 140
      selector:
        number:
          min: 120
          max: 260
          unit_of_measurement: V

    restore_below:
      name: Limite inferior para religar (V)
      default: 119
      selector:
        number:
          min: 90
          max: 200
          unit_of_measurement: V

    restore_above:
      name: Limite superior para religar (V)
      default: 135
      selector:
        number:
          min: 110
          max: 260
          unit_of_measurement: V

    stabilize_time:
      name: Tempo de tensão estável (min)
      default: 3
      selector:
        number:
          min: 1
          max: 30

    compressor_delay:
      name: Tempo mínimo compressor desligado (min)
      default: 10
      selector:
        number:
          min: 0
          max: 30

mode: single

variables:
  plug_entity: !input plug
  voltage_entity: !input voltage_sensor
  v: "{{ states(voltage_entity) | float(0) }}"

trigger:
  - platform: numeric_state
    entity_id: !input voltage_sensor
    below: !input cut_below

  - platform: numeric_state
    entity_id: !input voltage_sensor
    above: !input cut_above

  - platform: numeric_state
    entity_id: !input voltage_sensor
    above: !input restore_below
    below: !input restore_above
    for:
      minutes: !input stabilize_time

action:
  - choose:

      # DESLIGAR SOMENTE SE TENSÃO REALMENTE ESTIVER FORA
      - conditions:
          - condition: template
            value_template: >
              {{ (v < (!input cut_below)) or (v > (!input cut_above)) }}
          - condition: state
            entity_id: !input plug
            state: "on"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input plug

          - service: counter.increment
            target:
              entity_id: !input surge_counter

          - service: notify.notify
            data:
              title: "Proteção de Tensão"
              message: "Tomada desligada por tensão fora do limite."

      # RELIGAR SOMENTE SE TENSÃO REALMENTE ESTIVER SEGURA
      - conditions:
          - condition: template
            value_template: >
              {{ (!input restore_below) <= v <= (!input restore_above) }}
          - condition: state
            entity_id: !input plug
            state: "off"
        sequence:
          - delay:
              minutes: !input compressor_delay

          - service: switch.turn_on
            target:
              entity_id: !input plug

          - service: notify.notify
            data:
              title: "Energia Restabelecida"
              message: "Tomada religada com segurança."
